---
name: docker
on:
  push:
  pull_request:
jobs:
  docker:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: docker build . -t ghcr.io/satcomx00-x00/squid-proxy:latest -t ghcr.io/satcomx00-x00/squid-proxy:1.0
